name: CI

on:
  push:
    branches: ['main']

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev tools
        run: brew install coreutils tree

      - name: Download libsodium Latest Tarball
        run: wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
        env:
          TIMEOUT_MODE: disable

      - name: Extract Tarball
        run: |
             tar -xvzf LATEST.tar.gz

      - run: ls

      - name: Build MacOS 
        run: |
              cd libsodium-stable
              chmod +x ../scripts/build-libsodium.sh && ../scripts/build-libsodium.sh
        env: 
            LIBSODIUM_MINIMAL_BUILD: true

      - run: |
             ls ./libsodium-stable/libsodium-apple/macos
             tree ./libsodium-stable/libsodium-apple/macos
      
      - name: Push libsodium Binaries to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsodium-macos
          path: |
             libsodium-stable/libsodium-apple/macos/lib
             libsodium-stable/libsodium-apple/macos/build_log
             libsodium-stable/libsodium-apple/macos/debug_log
