name: CI

on:
  push:
    branches: ['main']

jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev tools
        run: brew install coreutils

      - name: Install luvit
        run: git clone https://github.com/jedisct1/libsodium.git
        env:
          TIMEOUT_MODE: disable

      - name: Build binaries
        run: cd libsodium && ./dist-build/apple-xcframework.sh
        env:
          DOT_ENABLE: true
