name: CI

on:
  push:
    branches: ['main']

jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dev tools
        run: brew install coreutils tree

      - name: Clone Repo
        run: wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
        env:
          TIMEOUT_MODE: disable

      - name: extract 
        run: |
             tar -xvzf LATEST.tar.gz

      - run: ls

      - name: Build MacOS 
        run: |
              cd libsodium-stable
              ./dist-build/macos.sh
        env: 
            LIBSODIUM_MINIMAL_BUILD: true
            LIBSODIUM_SKIP_SIMULATORS: "true"

      - run: |
             ls ./libsodium/builds
             tree ./libsodium

      - name: cat Log files
        run: |
              cd libsodium/libsodium-osx
              ls